Repository mesh-adaptation/movement, pull requests merged in 2024-09, with the labels that each got.

#115 Fix specific boundary segments under MA
  movement/monge_ampere.py
  movement/mover.py
  test/test_monge_ampere.py
Labels: enhancement

#95 Better testing for Monge-Ampere boundary conditions
  movement/math.py
  movement/monge_ampere.py
  movement/mover.py
  pyproject.toml
  test/conftest.py
  test/test_math.py
  test/test_monge_ampere.py
  test/test_tangling.py
Labels: testing, PRIORITY

#123 Enable B and C linting rules
  movement/math.py
  movement/monge_ampere.py
  movement/mover.py
  movement/spring.py
  movement/tangling.py
  pyproject.toml
  test/monitors.py
  test/test_forced_movement.py
Labels: testing, clarity

#125 Use ghcr Docker image for CI
  .github/workflows/test_suite.yml
Labels: testing

#127 Expand workflows: citation check and changed-files
  .github/workflows/citation_check.yml
  .github/workflows/test_suite.yml
Labels: testing

#128 Fix changed-files pathing
  .github/workflows/test_suite.yml
Labels: bug

#129 Use reusable workflows
  .github/workflows/citation_check.yml
  .github/workflows/test_suite.yml
  Makefile
Labels: testing
