Repository mesh-adaptation/movement, pull requests merged in 2024-06, with the labels that each got.

#92 Option for raising warning if not converged
  movement/laplacian_smoothing.py
  movement/monge_ampere.py
  movement/mover.py
  movement/spring.py
  test/test_monge_ampere.py
Labels: enhancement

#98 Minor demo and readme fixes
  README.md
  demos/laplacian_smoothing.py
  demos/lineal_spring.py
  demos/monge_ampere1.py
  demos/monge_ampere_3d.py
  demos/monge_ampere_helmholtz.py
Labels: documentation

#100 Unit tests for spring-based methods
  movement/spring.py
  test/test_spring.py
Labels: testing, PRIORITY
