Repository mesh-adaptation/movement, pull requests merged in 2024-07, with the labels that each got.

#104 Separate out diagnostics
  demos/laplacian_smoothing.py
  demos/lineal_spring.py
  demos/monge_ampere1.py
  demos/monge_ampere_helmholtz.py
  movement/laplacian_smoothing.py
  movement/monge_ampere.py
  movement/mover.py
  movement/spring.py
Labels: refactor

#103 Use mesh tangling checker
  movement/laplacian_smoothing.py
  movement/monge_ampere.py
  movement/mover.py
  movement/spring.py
  movement/tangling.py
  test/test_monge_ampere.py
  test/test_spring.py
Labels: bug

#108 Run shortened test demos directly
  .github/workflows/test_suite.yml
  demos/monge_ampere1.py
  demos/monge_ampere_3d.py
  demos/monge_ampere_helmholtz.py
  test/test_demos.py
Labels: testing, clarity

#109 Refactor `PrimeMover`
  movement/mover.py
  movement/spring.py
  test/test_monge_ampere.py
  test/test_tangling.py
Labels: testing, refactor

#111 Unit tests for Laplacian smoothing
  movement/laplacian_smoothing.py
  test/test_forced_movement.py
  test/test_laplacian_smoothing.py
  test/test_spring.py
Labels: testing, refactor
