Repository mesh-adaptation/movement, pull requests merged in 2024-04, with the labels that each got.

#65 Add Monge-Ampere zoom plot and tangling exercise
  demos/monge_ampere1.py
  movement/tangling.py
  test/test_tangling.py
Labels: documentation, testing, PRIORITY, refactor

#63 Extend MA mover to 3D and add demo
  demos/demo_references.bib
  demos/monge_ampere1.py
  demos/monge_ampere_3d-paraview.jpg
  demos/monge_ampere_3d.py
  demos/monge_ampere_helmholtz.py
  movement/monge_ampere.py
  movement/mover.py
  test/monitors.py
  test/test_monge_ampere.py
Labels: documentation, enhancement

#60 Laplacian smoothing demo
  demos/laplacian_smoothing.py
  demos/lineal_spring.py
  movement/__init__.py
  movement/laplacian.py
  movement/laplacian_smoothing.py
  movement/spring.py
  test/data/forced_mesh_laplacian.npy
  test/data/forced_mesh_lineal_4.npy
  test/test_smoothing.py
  test/test_spring.py
Labels: documentation

#68 Expand use of `pyproject.toml`; expand `README.md`
  .flake8
  .github/workflows/test_suite.yml
  .gitignore
  .pre-commit-config.yaml
  Makefile
  README.md
  demos/laplacian_smoothing.py
  demos/lineal_spring.py
  demos/monge_ampere1.py
  demos/monge_ampere_3d.py
  demos/monge_ampere_helmholtz.py
  movement/laplacian_smoothing.py
  movement/monge_ampere.py
  movement/mover.py
  movement/spring.py
  movement/tangling.py
  pyproject.toml
  requirements.txt
  setup.py
  test/test_demos.py
  test/test_monge_ampere.py
  test/test_spring.py
  test/test_tangling.py
Labels: documentation, install

#76 Fix Laplacian smoothing demo formatting
  .github/workflows/test_suite.yml
  demos/laplacian_smoothing.py
Labels: bug, documentation, testing
