Repository mesh-adaptation/movement, pull requests merged in 2024-12, with the labels that each got.

#136 Fix path to docs repo
  .github/workflows/test_suite.yml
Labels: bug, testing, PRIORITY

#137 Simplify test workflow file
  .github/workflows/test_suite.yml
Labels: testing, clarity

#139 Fix for failing tests since new Firedrake update
  movement/monge_ampere.py
  movement/spring.py
  test/test_spring.py
Labels: bug, PRIORITY

#134 Check for mesh element type with spring-based method
  movement/spring.py
  test/test_monge_ampere.py
  test/test_spring.py
Labels: bug

#126 Drop lint ignores
  demos/laplacian_smoothing.py
  demos/lineal_spring.py
  demos/monge_ampere1.py
  demos/monge_ampere_3d.py
  demos/monge_ampere_helmholtz.py
  movement/laplacian_smoothing.py
  movement/monge_ampere.py
  movement/spring.py
  pyproject.toml
  test/monitors.py
  test/test_forced_movement.py
  test/test_laplacian_smoothing.py
  test/test_monge_ampere.py
  test/test_spring.py
  test/test_tangling.py
Labels: enhancement
