Repository mesh-adaptation/movement, pull requests merged in 2025-01, with the labels that each got.

#143 Introduce optional dev dependencies
  .github/workflows/test_suite.yml
  Makefile
  pyproject.toml
Labels: install

#144 Doubly periodic MA demo
  demos/monge_ampere_3d.py
  demos/monge_ampere_periodic.py
  demos/monge_ampere_ring.py
  test/test_demos.py
Labels: documentation, testing

#145 Expand MA Helmholtz demo to interpolate soln field
  demos/monge_ampere_helmholtz.py
Labels: documentation, PRIORITY

#147 Switch to comp coords before moving with QN
  movement/monge_ampere.py
Labels: bug, PRIORITY

#142 Implement `MeshTanglingChecker` in 1D and 3D
  movement/mover.py
  movement/tangling.py
  test/test_tangling.py
Labels: enhancement
